# Documentation at http://goreleaser.com
env_files:
  github_token: ~/.github-tokens/heimatcli
before:
  hooks:
    # you may remove this if you don't use vgo
    # - go mod download
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
  - main: ./src/cmd
    binary: heimat
    env:
      - CGO_ENABLED=0
    # https://golang.org/doc/install/source#environment
    goos:
      - linux
      # - windows
      - darwin
    # https://golang.org/doc/install/source#environment
    goarch:
      - amd64
      - arm
      - arm64

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      # windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - tap:
      owner: sprinteins
      name: heimatcli
  - description: "A CLI/REPL Client for Heimat"
