# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Heimatcli < Formula
  desc ""
  homepage ""
  version "0.1.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/sprinteins/heimatcli/releases/download/v0.1.1/heimatcli_0.1.1_Darwin_x86_64.tar.gz"
    sha256 "b9542c921388106784772884bd236094b1d3687dbf58a239295da33fdc4c8330"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/sprinteins/heimatcli/releases/download/v0.1.1/heimatcli_0.1.1_Linux_x86_64.tar.gz"
    sha256 "e641414a7671528b05d5b079a75cc9bf0fc33c553fc84d269390364cc623afc2"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/sprinteins/heimatcli/releases/download/v0.1.1/heimatcli_0.1.1_Linux_arm64.tar.gz"
    sha256 "b51d0e32468ef963d222675d0ea33622e36c56ea5809b90e2cdcc6c2fd7a65f0"
  end

  def install
    bin.install "heimatcli"
  end
end
