# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Heimatcli < Formula
  desc ""
  homepage ""
  version "0.1.3"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/sprinteins/heimatcli/releases/download/v0.1.3/heimatcli_0.1.3_Darwin_x86_64.tar.gz"
    sha256 "69aca703da6cf4bc01a60e9ef3df2b753ec102dabe25ab1c3a2d5570b0dad21d"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/sprinteins/heimatcli/releases/download/v0.1.3/heimatcli_0.1.3_Linux_x86_64.tar.gz"
    sha256 "3a2e47c25350b63d78b805e45190f9f6412afc4e00919c9ba3a6654625623332"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/sprinteins/heimatcli/releases/download/v0.1.3/heimatcli_0.1.3_Linux_arm64.tar.gz"
    sha256 "a8c93c7643957f4685c7267b0e403e932ae8427d17ecc66f7aac49e0132dd5e2"
  end

  def install
    bin.install "heimatcli"
  end
end
